### PR TITLE
use truncated content as excerpt if excerpt is empty

### PR DESCRIPTION
**Pull request by artchen**
The excerpt might be empty if no `<!--more-->` is present. In this case, use truncated and stripped content as excerpt. 
@LouisBarranqueiro

---

This change is [Reviewable](https://reviewable.io/reviews/louisbarranqueiro/hexo-algoliasearch/7)

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Dammm, I didn't receive any notification for this PR.

**Comment by artchen** [comment]
Quotes are changed. Also added optional config option excerptLimit and excerptSeparator - better compatibility for non-English blogs.

**Comment by LouisBarranqueiro** [comment]
Great. Could you update documentation, please?

**Comment by LouisBarranqueiro** [comment]
I added a `truncate` filter, so users can use it to cut excerpt incase there is no `<!--more-->` comment. E.g: `excerpt:strip:truncate,0,200`. So we don't need that `excerptLimit` anymore.

**Pull request closed without merging**
